name: Code-Checks
on: [ push ]

jobs:
  gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./gradlew
      - run: ./gradlew test


  check-ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.37.2/ktlint &&
          chmod a+x ktlint
      - run: ./ktlint